// ════════════════════════════════════════════════════════════════════════
// EVENTS · BEVERAGES — standalone section data (own My Plan: eventSelectedBeverages)
// Lives as sections/beveragesData.js. Load via <script> in index.html BEFORE events.js,
// which reads these two globals to render the Beverages sub-feature.
// Shape mirrors CAKES: id/name/emoji/category/serves/minGuests/glassware/serveNote/base300/method/tip.
// ════════════════════════════════════════════════════════════════════════

const BEVERAGE_CATEGORIES = [
  { id:"punches", label:"🥤 Punches & Jugs", desc:"Big-batch crowd-pleasers in a bowl or jug" },
  { id:"cocktails", label:"🍸 Cocktails", desc:"Batched bar classics for the grown-ups" },
  { id:"shooters", label:"🥃 Shooters", desc:"Quick, fun and a little cheeky" },
  { id:"mocktails", label:"🍹 Mocktails & Soft", desc:"Alcohol-free — kids, drivers & everyone" },
  { id:"homemade", label:"🥛 Homemade & Cream", desc:"Made-from-scratch liqueurs & indulgent drinks" },
  { id:"hot", label:"☕ Hot Drinks", desc:"Coffee, tea & winter warmers" },
  { id:"bubbly", label:"🥂 Welcome & Bubbly", desc:"Arrival drinks & toasts" },
];

const EVENTS_BEVERAGE_RECIPES = [
  // ── COCKTAILS & MOCKTAIL (new batch, 28 Jun 2026) ──

  /* ── from the approved sample ── */
  { id:"negroni", name:"Negroni", emoji:"🍊", category:"cocktails", serves:"10", minGuests:8, glassware:"Rocks glasses", serveNote:"Equal parts — stir over ice, never shake, to keep it clear",
    didYouKnow:"Invented in Florence in 1919 when Count Camillo Negroni asked for his Americano made with gin instead of soda — the barman swapped the lemon for an orange slice to mark the change.",
    base300:[{n:"Gin",a:"30ml per glass · 300ml per 10"},{n:"Campari",a:"30ml per glass · 300ml per 10"},{n:"Sweet red vermouth",a:"30ml per glass · 300ml per 10"},{n:"— GARNISH:",a:""},{n:"Orange slice",a:"1 per glass"},{n:"Ice (cubed)",a:"plenty"}],
    method:["Fill a rocks glass with ice.","Add equal parts gin, Campari and sweet vermouth.","Stir 20–30 seconds to chill.","Garnish with an orange slice."],
    tip:"Batch ahead: mix equal parts in a bottle, chill, pour over ice to serve a crowd fast." },

  { id:"whiskysour", name:"Whisky Sour", emoji:"🥃", category:"cocktails", serves:"10", minGuests:8, glassware:"Rocks glasses", serveNote:"Shake hard with ice — a good sour is ice-cold and frothy",
    didYouKnow:"The 'sour' — spirit, citrus and sugar — is one of the oldest cocktail templates in print, appearing in Jerry Thomas's 1862 Bartenders Guide.",
    base300:[{n:"Bourbon or whisky",a:"50ml per glass · 500ml per 10"},{n:"Fresh lemon juice",a:"25ml per glass · 250ml per 10"},{n:"Sugar syrup",a:"15ml per glass · 150ml per 10"},{n:"Egg white (optional, for froth)",a:"1 per 2 glasses"},{n:"— GARNISH:",a:""},{n:"Angostura bitters",a:"a few drops per glass"},{n:"Lemon slice & cherry",a:"1 per glass"}],
    method:["If using egg white, dry-shake (no ice) first to build froth.","Add ice and shake hard with whisky, lemon and sugar syrup.","Strain over fresh ice.","Dot the foam with bitters and garnish."],
    tip:"No egg white? A splash of aquafaba (chickpea water) gives the same silky foam." },

  { id:"tomcollins", name:"Tom Collins", emoji:"🍸", category:"cocktails", serves:"10", minGuests:8, glassware:"Tall / Collins glasses", serveNote:"Build it tall over ice and top with soda last",
    didYouKnow:"Named after an 1874 New York hoax where strangers sent you chasing a 'Tom Collins' who was badmouthing you — bartenders turned the joke into a drink.",
    base300:[{n:"Gin",a:"50ml per glass · 500ml per 10"},{n:"Fresh lemon juice",a:"25ml per glass · 250ml per 10"},{n:"Sugar syrup",a:"15ml per glass · 150ml per 10"},{n:"Soda water (to top)",a:"80ml per glass · 800ml per 10"},{n:"— GARNISH:",a:""},{n:"Lemon slice & cherry",a:"1 per glass"}],
    method:["Build gin, lemon and sugar syrup over ice in a tall glass.","Top with soda water.","Stir gently.","Garnish with lemon and cherry."],
    tip:"Swap gin for vodka and it's a Vodka Collins; for whisky, a John Collins." },

  { id:"tequilasunrise", name:"Tequila Sunrise", emoji:"🌅", category:"cocktails", serves:"10", minGuests:8, glassware:"Tall glasses", serveNote:"Pour the grenadine slowly so it sinks and 'rises' — don't stir",
    didYouKnow:"The modern version was made at the Trident bar in California in the 1970s and became the Rolling Stones' drink on their 1972 tour — Mick Jagger called it the 'cocktail tour'.",
    base300:[{n:"Tequila",a:"50ml per glass · 500ml per 10"},{n:"Orange juice",a:"100ml per glass · 1L per 10"},{n:"Grenadine",a:"10ml per glass · 100ml per 10"},{n:"— GARNISH:",a:""},{n:"Orange slice & cherry",a:"1 per glass"}],
    method:["Fill a tall glass with ice.","Add tequila and orange juice.","Slowly pour grenadine down the inside so it sinks.","Leave to rise — don't stir. Garnish."],
    tip:"The unstirred grenadine is the whole point — that's the sunrise.",
    versions:[
      {name:"Classic", icon:"🌅", default:true,
        base300:[{n:"Tequila",a:"50ml per glass · 500ml per 10"},{n:"Orange juice",a:"100ml per glass · 1L per 10"},{n:"Grenadine",a:"10ml per glass · 100ml per 10"},{n:"— GARNISH:",a:""},{n:"Orange slice & cherry",a:"1 per glass"}],
        method:["Fill a tall glass with ice.","Add tequila and orange juice.","Slowly pour grenadine down the inside so it sinks.","Leave to rise — don't stir. Garnish."]},
      {name:"Mocktail", icon:"🧃", serveNote:"🧒 Alcohol-free — same beautiful sunrise, kids' and drivers' favourite.",
        base300:[{n:"Orange juice",a:"130ml per glass · 1.3L per 10"},{n:"Soda water (a splash)",a:"30ml per glass · 300ml per 10"},{n:"Grenadine",a:"10ml per glass · 100ml per 10"},{n:"— GARNISH:",a:""},{n:"Orange slice & cherry",a:"1 per glass"}],
        method:["Fill a tall glass with ice.","Add orange juice and a splash of soda.","Slowly pour grenadine down the inside so it sinks.","Leave to rise — don't stir. Garnish."]}
    ] },

  /* ── new cocktails ── */
  { id:"martini", name:"Martini", emoji:"🍸", category:"cocktails", serves:"10", minGuests:8, glassware:"Martini glasses", serveNote:"Stir with ice and strain — keep it ice-cold and crystal clear",
    didYouKnow:"Shaken or stirred? Classic bartending says STIR a Martini — shaking clouds it with ice shards. James Bond's 'shaken, not stirred' was his own quirk, not the rule.",
    base300:[{n:"Gin (or vodka)",a:"60ml per glass · 600ml per 10"},{n:"Dry vermouth",a:"10ml per glass · 100ml per 10"},{n:"— GARNISH:",a:""},{n:"Olives or lemon twist",a:"1–2 per glass"}],
    method:["Stir gin and dry vermouth with plenty of ice for 20–30 seconds.","Strain into a chilled martini glass.","Garnish with olives or a lemon twist.","For a 'dry' martini, use less vermouth; 'dirty', add a splash of olive brine."],
    tip:"Chill the glasses in the freezer first — a warm martini is a sad martini." },

  { id:"harveywallbanger", name:"Harvey Wallbanger", emoji:"🍊", category:"cocktails", serves:"10", minGuests:8, glassware:"Tall glasses", serveNote:"Float the Galliano on top — that golden layer is the signature",
    didYouKnow:"A 1970s disco-era classic — basically a Screwdriver with a float of Galliano, the tall golden Italian vanilla-herb liqueur.",
    base300:[{n:"Vodka",a:"45ml per glass · 450ml per 10"},{n:"Orange juice",a:"90ml per glass · 900ml per 10"},{n:"Galliano (to float)",a:"15ml per glass · 150ml per 10"},{n:"— GARNISH:",a:""},{n:"Orange slice & cherry",a:"1 per glass"}],
    method:["Fill a tall glass with ice.","Add vodka and orange juice, stir.","Gently float the Galliano on top over the back of a spoon.","Garnish with orange and a cherry."],
    tip:"No Galliano? A little vanilla syrup gives a similar warm, golden note." },

  { id:"sidecar", name:"Sidecar", emoji:"🍋", category:"cocktails", serves:"10", minGuests:8, glassware:"Coupe glasses (sugar-rimmed)", serveNote:"Shake hard and strain — sharp, citrussy and elegant",
    didYouKnow:"A Prohibition-era classic said to be named after an army captain who arrived at a Paris bar in a motorcycle sidecar.",
    base300:[{n:"Cognac or brandy",a:"50ml per glass · 500ml per 10"},{n:"Cointreau / triple sec",a:"20ml per glass · 200ml per 10"},{n:"Fresh lemon juice",a:"20ml per glass · 200ml per 10"},{n:"— GARNISH:",a:""},{n:"Sugar (for the rim)",a:"a little per glass"},{n:"Lemon twist",a:"1 per glass"}],
    method:["Rim the glass with sugar and chill it.","Shake brandy, Cointreau and lemon hard with ice.","Strain into the sugar-rimmed coupe.","Garnish with a lemon twist."],
    tip:"SA brandy shines here — it's a great way to dress up a local bottle." },

  { id:"gimlet", name:"Gimlet", emoji:"🍈", category:"cocktails", serves:"10", minGuests:8, glassware:"Coupe glasses", serveNote:"Sharp, clean and bracing — gin and lime, nothing to hide behind",
    didYouKnow:"Once a British navy drink — gin cut with lime cordial to ward off scurvy on long voyages.",
    base300:[{n:"Gin",a:"60ml per glass · 600ml per 10"},{n:"Lime cordial",a:"20ml per glass · 200ml per 10"},{n:"— GARNISH:",a:""},{n:"Lime wheel",a:"1 per glass"}],
    method:["Shake gin and lime cordial with ice until very cold.","Strain into a chilled coupe.","Garnish with a lime wheel.","Prefer fresh? Use 25ml fresh lime juice + 15ml sugar syrup instead of cordial."],
    tip:"A vodka gimlet works just as well for non-gin drinkers." },

  { id:"maitai", name:"Mai Tai", emoji:"🌺", category:"cocktails", serves:"10", minGuests:8, glassware:"Rocks glasses (crushed ice)", serveNote:"Pile on crushed ice — it's a tiki drink, lean into it",
    didYouKnow:"Created by Trader Vic in 1944 — legend says the first taster, a friend from Tahiti, exclaimed 'Maita'i!' (Tahitian for 'very good').",
    base300:[{n:"Aged / dark rum",a:"40ml per glass · 400ml per 10"},{n:"Orange curaçao",a:"20ml per glass · 200ml per 10"},{n:"Orgeat (almond syrup)",a:"15ml per glass · 150ml per 10"},{n:"Fresh lime juice",a:"25ml per glass · 250ml per 10"},{n:"— GARNISH:",a:""},{n:"Mint sprig & lime shell",a:"1 per glass"}],
    method:["Shake rum, curaçao, orgeat and lime with crushed ice.","Pour unstrained into a rocks glass.","Top with more crushed ice.","Garnish with a mint sprig and a spent lime shell."],
    tip:"Float a little extra dark rum on top for a 'shipwreck' finish." },

  { id:"passionfruitmartini", name:"Passionfruit Martini", emoji:"🍹", category:"cocktails", serves:"10", minGuests:8, glassware:"Martini glasses (+ shot glasses)", serveNote:"Serve with a side shot of bubbly — sip, shot, sip",
    didYouKnow:"A modern London classic from the early 2000s — on most bar menus it's the cheekily-named 'Pornstar Martini'. Always served with a little shot of prosecco on the side.",
    base300:[{n:"Vanilla vodka",a:"50ml per glass · 500ml per 10"},{n:"Passionfruit purée (or Passoã)",a:"25ml per glass · 250ml per 10"},{n:"Fresh lime juice",a:"15ml per glass · 150ml per 10"},{n:"Vanilla sugar syrup",a:"10ml per glass · 100ml per 10"},{n:"Prosecco (side shot)",a:"30ml per glass · 300ml per 10"},{n:"— GARNISH:",a:""},{n:"Half a fresh passionfruit",a:"½ per glass"}],
    method:["Shake the vodka, passionfruit, lime and vanilla syrup hard with ice.","Strain into a chilled martini glass.","Float half a fresh passionfruit on top.","Serve with a small side shot of prosecco."],
    tip:"Pour the prosecco shot last so it's lively." },

  { id:"singaporesling", name:"Singapore Sling", emoji:"🍒", category:"cocktails", serves:"10", minGuests:8, glassware:"Tall / Hurricane glasses", serveNote:"Long, fruity and ruby-red — a proper holiday drink",
    didYouKnow:"Created around 1915 at the Raffles Hotel in Singapore — its pink colour let ladies of the era 'drink' in public when alcohol wasn't proper for them.",
    base300:[{n:"Gin",a:"30ml per glass · 300ml per 10"},{n:"Cherry liqueur",a:"15ml per glass · 150ml per 10"},{n:"Pineapple juice",a:"100ml per glass · 1L per 10"},{n:"Fresh lime juice",a:"15ml per glass · 150ml per 10"},{n:"Grenadine",a:"10ml per glass · 100ml per 10"},{n:"— GARNISH:",a:""},{n:"Angostura bitters",a:"a dash per glass"},{n:"Pineapple wedge & cherry",a:"1 per glass"}],
    method:["Shake gin, cherry liqueur, pineapple, lime and grenadine with ice.","Strain into a tall glass over fresh ice.","Add a dash of bitters.","Garnish with a pineapple wedge and cherry."],
    tip:"A splash of soda lengthens it nicely for a hot day." },

  { id:"oldfashioned", name:"Old Fashioned", emoji:"🥃", category:"cocktails", serves:"10", minGuests:8, glassware:"Rocks glasses", serveNote:"Spirit-forward — stir slowly over a big ice cube",
    didYouKnow:"One of the very first drinks to be called a 'cocktail' in the early 1800s — whisky, sugar, water and bitters. When fancier drinks took over, drinkers asked for it the 'old-fashioned' way.",
    base300:[{n:"Bourbon or whisky",a:"50ml per glass · 500ml per 10"},{n:"Sugar syrup",a:"10ml per glass · 100ml per 10"},{n:"Angostura bitters",a:"2–3 dashes per glass"},{n:"— GARNISH:",a:""},{n:"Orange peel",a:"1 per glass"}],
    method:["Add sugar syrup and bitters to a rocks glass.","Add the whisky and a large ice cube.","Stir slowly for 20–30 seconds.","Express an orange peel over the top and drop it in."],
    tip:"A big single ice cube melts slower — less dilution, more flavour." },

  { id:"moscowmule", name:"Moscow Mule", emoji:"🫚", category:"cocktails", serves:"10", minGuests:8, glassware:"Copper mugs / tall glasses", serveNote:"Spicy ginger kick — serve really cold, ideally in a copper mug",
    didYouKnow:"Born in 1941 Los Angeles to shift unsold vodka and ginger beer — the copper mug was a third struggling product the trio threw into the deal.",
    base300:[{n:"Vodka",a:"50ml per glass · 500ml per 10"},{n:"Fresh lime juice",a:"15ml per glass · 150ml per 10"},{n:"Ginger beer (to top)",a:"120ml per glass · 1.2L per 10"},{n:"— GARNISH:",a:""},{n:"Lime wedge & mint",a:"1 per glass"}],
    method:["Fill a copper mug or tall glass with ice.","Add vodka and lime juice.","Top with ginger beer.","Garnish with a lime wedge and mint."],
    tip:"Use a fiery ginger beer, not ginger ale — the spice is the point.",
    versions:[
      {name:"Classic", icon:"🫚", default:true,
        base300:[{n:"Vodka",a:"50ml per glass · 500ml per 10"},{n:"Fresh lime juice",a:"15ml per glass · 150ml per 10"},{n:"Ginger beer (to top)",a:"120ml per glass · 1.2L per 10"},{n:"— GARNISH:",a:""},{n:"Lime wedge & mint",a:"1 per glass"}],
        method:["Fill a mug with ice.","Add vodka and lime.","Top with ginger beer.","Garnish."]},
      {name:"Mocktail", icon:"🧒", serveNote:"🧒 Alcohol-free Virgin Mule — all the ginger kick, no vodka.",
        base300:[{n:"Fresh lime juice",a:"20ml per glass · 200ml per 10"},{n:"Ginger beer (to top)",a:"160ml per glass · 1.6L per 10"},{n:"— GARNISH:",a:""},{n:"Lime wedge & mint",a:"1 per glass"}],
        method:["Fill a mug with ice.","Add the lime juice.","Top with ginger beer.","Garnish with lime and mint."]}
    ] },

  { id:"martinez", name:"Martinez", emoji:"🍒", category:"cocktails", serves:"10", minGuests:8, glassware:"Coupe glasses", serveNote:"The smooth, sweet grandfather of the Martini — stir and strain",
    didYouKnow:"Widely seen as the bridge between the Manhattan and the Martini — richer and sweeter than today's dry Martini.",
    base300:[{n:"Gin",a:"45ml per glass · 450ml per 10"},{n:"Sweet red vermouth",a:"45ml per glass · 450ml per 10"},{n:"Maraschino liqueur",a:"7ml per glass · 70ml per 10"},{n:"— GARNISH:",a:""},{n:"Angostura bitters",a:"2 dashes per glass"},{n:"Lemon twist",a:"1 per glass"}],
    method:["Stir gin, vermouth, maraschino and bitters with ice.","Strain into a chilled coupe.","Express a lemon twist over the top and drop it in."],
    tip:"Use an Old Tom or floral gin for the most authentic, rounded flavour." },

  { id:"sazerac", name:"Sazerac", emoji:"🥃", category:"cocktails", serves:"10", minGuests:8, glassware:"Rocks glasses (chilled)", serveNote:"Rinse the glass with absinthe, tip it out, then build — that aroma is everything",
    didYouKnow:"New Orleans' signature cocktail and one of America's oldest, dating to the 1850s — originally made with cognac before rye whisky took over.",
    base300:[{n:"Rye whisky (or cognac)",a:"50ml per glass · 500ml per 10"},{n:"Sugar syrup",a:"10ml per glass · 100ml per 10"},{n:"Peychaud's bitters",a:"3 dashes per glass"},{n:"Absinthe (to rinse)",a:"a splash per glass"},{n:"— GARNISH:",a:""},{n:"Lemon peel",a:"1 per glass"}],
    method:["Rinse a chilled rocks glass with absinthe and tip out the excess.","Stir the whisky, sugar and Peychaud's with ice.","Strain into the absinthe-rinsed glass (no ice).","Express a lemon peel over the top — traditionally discarded, not dropped in."],
    tip:"No Peychaud's? Angostura works, though the flavour shifts a little." },

  { id:"bloodymary", name:"Bloody Mary", emoji:"🍅", category:"cocktails", serves:"10", minGuests:8, glassware:"Tall glasses", serveNote:"Savoury and spicy — adjust the heat to taste, garnish generously",
    didYouKnow:"The ultimate brunch and hangover drink, made famous at Harry's New York Bar in 1920s Paris. The celery-stick garnish was a 1960s Chicago addition.",
    base300:[{n:"Vodka",a:"45ml per glass · 450ml per 10"},{n:"Tomato juice",a:"90ml per glass · 900ml per 10"},{n:"Fresh lemon juice",a:"15ml per glass · 150ml per 10"},{n:"Worcestershire sauce",a:"2 dashes per glass"},{n:"Tabasco",a:"to taste"},{n:"— SEASONING & GARNISH:",a:""},{n:"Salt, pepper & celery salt",a:"a pinch per glass"},{n:"Celery stick & lemon",a:"1 per glass"}],
    method:["Fill a tall glass with ice.","Add vodka, tomato juice, lemon, Worcestershire and Tabasco.","Season with salt, pepper and celery salt; stir (or 'roll' between two glasses).","Garnish with a celery stick and lemon wedge."],
    tip:"A pinch of smoked paprika or a dash of pickle brine adds real depth.",
    versions:[
      {name:"Classic", icon:"🍅", default:true,
        base300:[{n:"Vodka",a:"45ml per glass · 450ml per 10"},{n:"Tomato juice",a:"90ml per glass · 900ml per 10"},{n:"Fresh lemon juice",a:"15ml per glass · 150ml per 10"},{n:"Worcestershire sauce",a:"2 dashes per glass"},{n:"Tabasco",a:"to taste"},{n:"— SEASONING & GARNISH:",a:""},{n:"Salt, pepper & celery salt",a:"a pinch per glass"},{n:"Celery stick & lemon",a:"1 per glass"}],
        method:["Fill a tall glass with ice.","Add vodka, tomato juice, lemon, Worcestershire and Tabasco.","Season and stir.","Garnish with celery and lemon."]},
      {name:"Mocktail", icon:"🧒", serveNote:"🧒 Alcohol-free Virgin Mary — all the savoury kick, no vodka.",
        base300:[{n:"Tomato juice",a:"130ml per glass · 1.3L per 10"},{n:"Fresh lemon juice",a:"15ml per glass · 150ml per 10"},{n:"Worcestershire sauce",a:"2 dashes per glass"},{n:"Tabasco",a:"to taste"},{n:"— SEASONING & GARNISH:",a:""},{n:"Salt, pepper & celery salt",a:"a pinch per glass"},{n:"Celery stick & lemon",a:"1 per glass"}],
        method:["Fill a tall glass with ice.","Add tomato juice, lemon, Worcestershire and Tabasco.","Season and stir.","Garnish with celery and lemon."]}
    ] },

  { id:"vesper", name:"Vesper", emoji:"🕸️", category:"cocktails", serves:"10", minGuests:8, glassware:"Coupe glasses", serveNote:"Strong and elegant — gin, vodka and a whisper of Lillet",
    didYouKnow:"James Bond's own invention in Casino Royale (1953), named after Vesper Lynd — the one time 'shaken, not stirred' actually applies.",
    base300:[{n:"Gin",a:"60ml per glass · 600ml per 10"},{n:"Vodka",a:"15ml per glass · 150ml per 10"},{n:"Lillet Blanc",a:"7ml per glass · 70ml per 10"},{n:"— GARNISH:",a:""},{n:"Lemon twist",a:"1 per glass"}],
    method:["Shake gin, vodka and Lillet Blanc hard with ice until very cold.","Strain into a chilled coupe.","Express a large lemon twist over the top and drop it in."],
    tip:"Lillet Blanc has replaced the original (now-discontinued) Kina Lillet — a touch of dry vermouth also works." },

  /* ── Rock Shandy — non-alcoholic, lives in MOCKTAILS ── */
  { id:"rockshandy", name:"Rock Shandy", emoji:"🍋", category:"mocktails", serves:"10", minGuests:6, glassware:"Tall glasses", serveNote:"The SA classic — equal lemonade and soda with a dash of bitters",
    didYouKnow:"A South African and British favourite — half lemonade, half soda, with a few dashes of Angostura bitters for that signature pink tint and grown-up edge. Beloved at golf clubs and braais alike.",
    base300:[{n:"Lemonade",a:"150ml per glass · 1.5L per 10"},{n:"Soda water",a:"150ml per glass · 1.5L per 10"},{n:"Angostura bitters",a:"4–5 dashes per glass"},{n:"— GARNISH:",a:""},{n:"Lemon slice",a:"1 per glass"},{n:"Ice",a:"plenty"}],
    method:["Fill a tall glass with ice.","Pour in equal parts lemonade and soda water.","Add 4–5 dashes of Angostura bitters.","Stir once and garnish with a lemon slice."],
    tip:"The bitters are technically a trace of alcohol — leave them out entirely for a fully alcohol-free version for kids." },

  // ── PUNCHES & JUGS ──
  { id:"fruitpunch", name:"Fruit Punch", emoji:"🥤", category:"punches", serves:"20–25", minGuests:10, glassware:"Punch bowl + tumblers", serveNote:"Add the fizz only just before serving so it stays sparkling",
    didYouKnow:"The word \"punch\" comes from the Sanskrit and Hindi panch — \"five\" — for the five parts the original 17th-century drink always had: spirit, sugar, citrus, water and spice. East India Company sailors carried it home to England, and from there it spread across the world.",
    base300:[{n:"Orange juice",a:"100ml per glass · 2L per 20"},{n:"Pineapple juice",a:"60ml per glass · 1.2L per 20"},{n:"Red grape or cranberry juice",a:"40ml per glass · 800ml per 20"},{n:"Ginger ale or lemonade",a:"100ml per glass · 2L per 20"},{n:"— GARNISH:",a:""},{n:"Orange & lemon slices",a:"1 each per 4 glasses"},{n:"Fresh mint",a:"a few sprigs per bowl"},{n:"Ice",a:"plenty"}],
    method:["Chill all the juices well.","Mix the juices in a large punch bowl.","Add the sliced fruit and mint.","Top with ginger ale or lemonade and a big scoop of ice just before serving."],
    tip:"Freeze some of the punch into ice cubes so it doesn't water down as it melts.",
    versions:[
      {name:"Classic", icon:"🧃", default:true,
        base300:[{n:"Orange juice",a:"100ml per glass · 2L per 20"},{n:"Pineapple juice",a:"60ml per glass · 1.2L per 20"},{n:"Red grape or cranberry juice",a:"40ml per glass · 800ml per 20"},{n:"Ginger ale or lemonade",a:"100ml per glass · 2L per 20"},{n:"— GARNISH:",a:""},{n:"Orange & lemon slices",a:"1 each per 4 glasses"},{n:"Fresh mint",a:"a few sprigs per bowl"},{n:"Ice",a:"plenty"}],
        method:["Chill all the juices well.","Mix the juices in a large punch bowl.","Add the sliced fruit and mint.","Top with ginger ale or lemonade and a big scoop of ice just before serving."]},
      {name:"Summer Berries", icon:"🫐",
        base300:[{n:"White grape juice",a:"80ml per glass · 1.6L per 20"},{n:"Apple juice",a:"80ml per glass · 1.6L per 20"},{n:"Lemonade",a:"100ml per glass · 2L per 20"},{n:"Mixed fresh berries (straw/rasp/blue)",a:"300g per 20"},{n:"— GARNISH:",a:""},{n:"Lemon slices",a:"1 per 4 glasses"},{n:"Fresh mint",a:"a few sprigs per bowl"},{n:"Ice",a:"plenty"}],
        method:["Chill the grape and apple juice well.","Lightly crush a handful of the berries to release their colour, then mix all the juice in the bowl.","Add the whole berries, lemon slices and mint.","Top with lemonade and ice just before serving."]},
      {name:"Tropical", icon:"🍍",
        base300:[{n:"Pineapple juice",a:"100ml per glass · 2L per 20"},{n:"Mango juice",a:"60ml per glass · 1.2L per 20"},{n:"Granadilla pulp",a:"4 granadillas per 20"},{n:"Coconut cream",a:"a splash · 200ml per 20"},{n:"Soda water or lemonade",a:"80ml per glass · 1.6L per 20"},{n:"— GARNISH:",a:""},{n:"Pineapple chunks",a:"a handful per bowl"},{n:"Fresh mint",a:"a few sprigs per bowl"},{n:"Ice",a:"plenty"}],
        method:["Chill the pineapple and mango juice.","Mix the pineapple, mango and granadilla pulp in the bowl, then stir in the coconut cream.","Add the pineapple chunks and mint.","Top with soda or lemonade and plenty of ice just before serving."]},
      {name:"Sparkling Wine", icon:"🥂", serveNote:"🍷 Contains alcohol — adults only. Add the sparkling wine right at the end so it stays bubbly.",
        base300:[{n:"White grape or apple juice",a:"60ml per glass · 1.2L per 20"},{n:"Peach or orange juice",a:"40ml per glass · 800ml per 20"},{n:"Peach liqueur (optional)",a:"a splash · 250ml per 20"},{n:"Sparkling wine / Cap Classique",a:"120ml per glass · 3 bottles per 20"},{n:"— GARNISH:",a:""},{n:"Sliced peaches & strawberries",a:"a handful per bowl"},{n:"Fresh mint",a:"a few sprigs per bowl"},{n:"Ice",a:"plenty"}],
        method:["Chill everything really well — fizz holds better cold.","Mix the juice and peach liqueur in the bowl with the sliced fruit and let it sit 10 minutes to infuse.","Add ice.","Pour in the sparkling wine right at the table, just before serving, so it stays lively."]},
      {name:"Spiked", icon:"🍸", serveNote:"🍷 Contains alcohol — adults only. Spike the bowl, or pour a tot per glass.",
        base300:[{n:"Orange juice",a:"90ml per glass · 1.8L per 20"},{n:"Pineapple juice",a:"60ml per glass · 1.2L per 20"},{n:"Red grape or cranberry juice",a:"40ml per glass · 800ml per 20"},{n:"White rum or vodka",a:"1 tot 25ml per glass · 500ml per 20"},{n:"Ginger ale or lemonade",a:"80ml per glass · 1.6L per 20"},{n:"— GARNISH:",a:""},{n:"Orange & lemon slices",a:"1 each per 4 glasses"},{n:"Fresh mint",a:"a few sprigs per bowl"},{n:"Ice",a:"plenty"}],
        method:["Make the classic juice base in the bowl with the sliced fruit and mint.","Stir in the rum or vodka — a tot per glass, or about 500ml for a bowl of 20.","Top with ginger ale or lemonade and ice just before serving.","Keep a non-alcoholic jug alongside for kids and drivers."]}
    ] },
  { id:"sangria", name:"Sangria", emoji:"🍷", category:"punches", serves:"15–20", minGuests:10, glassware:"Jugs + wine glasses", serveNote:"Best made 2–4 hours ahead so the fruit infuses",
    base300:[{n:"Red wine (a fruity, inexpensive bottle)",a:"120ml per glass · 2.4L per 20"},{n:"Brandy",a:"15ml per glass · 300ml per 20"},{n:"Orange juice",a:"40ml per glass · 800ml per 20"},{n:"Sugar",a:"5g per glass · 100g per 20"},{n:"Soda water (to top)",a:"40ml per glass · 800ml per 20"},{n:"— FRUIT:",a:""},{n:"Orange (sliced)",a:"1 per jug"},{n:"Apple (diced)",a:"1 per jug"},{n:"Cinnamon stick",a:"1 per jug"}],
    method:["Stir the wine, brandy, orange juice and sugar in a jug until the sugar dissolves.","Add the sliced orange, diced apple and a cinnamon stick.","Chill 2–4 hours.","Top each glass with a splash of soda water and ice when serving."],
    tip:"For a white sangria, swap in a crisp white wine and add green apple and grapes." },
  { id:"pimms", name:"Pimm's Jug", emoji:"🍓", category:"punches", serves:"8–10", minGuests:8, glassware:"Tall jug + highball glasses", serveNote:"Add lemonade and ice at the last minute",
    base300:[{n:"Pimm's No.1",a:"50ml per glass · 500ml per 10"},{n:"Lemonade (Sprite/7-Up)",a:"150ml per glass · 1.5L per 10"},{n:"— GARNISH:",a:""},{n:"Cucumber (ribbons)",a:"1/3 per jug"},{n:"Strawberries (halved)",a:"4 per jug"},{n:"Orange (sliced)",a:"1/2 per jug"},{n:"Fresh mint",a:"a handful"}],
    method:["Fill a jug with ice.","Add the Pimm's, cucumber, strawberries, orange and mint.","Top with lemonade and stir gently.","Pour into ice-filled glasses with some fruit in each."],
    tip:"One part Pimm's to three parts lemonade is the classic ratio — adjust to taste." },
  { id:"icedrooibos", name:"Iced Rooibos Tea", emoji:"🧊", category:"punches", serves:"15–20", minGuests:10, glassware:"Glass dispenser + tumblers", serveNote:"Brew strong, then dilute over plenty of ice",
    base300:[{n:"Rooibos tea bags",a:"1 bag per 2 glasses · 10 bags per 20"},{n:"Boiling water",a:"100ml per glass · 2L per 20"},{n:"Sugar or honey",a:"5g per glass · 100g per 20"},{n:"Lemon (sliced)",a:"1 per jug"},{n:"Fresh mint",a:"a few sprigs"},{n:"Ice",a:"plenty"}],
    method:["Steep the rooibos in the boiling water 8–10 min for a strong brew.","Stir in the sugar or honey while hot.","Cool, then pour over plenty of ice.","Add lemon slices and mint to serve."],
    tip:"Naturally caffeine-free — great for an all-ages crowd and pretty in a glass dispenser." },
  { id:"brandypunch", name:"Brandy Punch", emoji:"🥃", category:"punches", serves:"15–20", minGuests:10, glassware:"Punch bowl + tumblers", serveNote:"A boozy classic — go easy, it's stronger than it tastes",
    base300:[{n:"Brandy",a:"45ml per glass · 900ml per 20"},{n:"Orange juice",a:"80ml per glass · 1.6L per 20"},{n:"Pineapple juice",a:"40ml per glass · 800ml per 20"},{n:"Lemonade or ginger ale (to top)",a:"60ml per glass · 1.2L per 20"},{n:"— GARNISH:",a:""},{n:"Orange & lemon slices",a:"a few per bowl"},{n:"Fresh mint",a:"a handful"},{n:"Ice",a:"plenty"}],
    method:["Mix the brandy and juices in a large punch bowl.","Chill well.","Top with lemonade or ginger ale and a big scoop of ice just before serving.","Float orange and lemon slices and mint on top."],
    tip:"Brandy punch sneaks up on people — keep a soft option alongside it." },
  { id:"sparklingberrypunch", name:"Sparkling Berry Punch", emoji:"🫐", category:"punches", serves:"20–25", minGuests:10, glassware:"Punch bowl + glasses", serveNote:"Non-alcoholic — kids and drivers love it",
    base300:[{n:"Mixed berry juice",a:"80ml per glass · 1.6L per 20"},{n:"Apple juice",a:"60ml per glass · 1.2L per 20"},{n:"Lemonade or sparkling water (to top)",a:"100ml per glass · 2L per 20"},{n:"— GARNISH:",a:""},{n:"Fresh or frozen berries",a:"a handful"},{n:"Lemon slices",a:"a few"},{n:"Fresh mint",a:"a few sprigs"}],
    method:["Mix the berry and apple juices in a punch bowl.","Chill well.","Top with lemonade or sparkling water just before serving.","Add frozen berries to keep it cold without watering it down."],
    tip:"Frozen berries double as ice cubes — pretty and they won't dilute it." },
  // ── COCKTAILS ──
  { id:"margarita", name:"Classic Margarita", emoji:"🍸", category:"cocktails", serves:"10–12", minGuests:8, glassware:"Salt-rimmed coupes/tumblers", serveNote:"Batch the liquid ahead; only add ice when you pour",
    base300:[{n:"Tequila",a:"45ml per glass · 540ml per 12"},{n:"Triple sec / Cointreau",a:"20ml per glass · 240ml per 12"},{n:"Fresh lime juice",a:"25ml per glass · 300ml per 12"},{n:"Sugar syrup",a:"10ml per glass · 120ml per 12"},{n:"— RIM & GARNISH:",a:""},{n:"Coarse salt",a:"for the rims"},{n:"Lime wedges",a:"1 per glass"}],
    method:["Mix the tequila, triple sec, lime juice and sugar syrup in a jug — this is your batch.","Rim the glasses: rub with lime and dip in salt.","To serve, shake portions with ice and strain into the glasses, or pour over ice.","Garnish with a lime wedge."],
    tip:"Pre-batch the liquid (no ice) and keep it cold; only add ice when you pour so it doesn't dilute." },
  { id:"mojito", name:"Mojito", emoji:"🌿", category:"cocktails", serves:"10", minGuests:8, glassware:"Highball glasses", serveNote:"Muddle the mint gently — bruise it, don't shred it",
    base300:[{n:"White rum",a:"50ml per glass · 500ml per 10"},{n:"Fresh lime juice",a:"25ml per glass · 250ml per 10"},{n:"Sugar syrup",a:"15ml per glass · 150ml per 10"},{n:"Soda water (to top)",a:"60ml per glass · 600ml per 10"},{n:"— GARNISH:",a:""},{n:"Fresh mint",a:"6 leaves per glass"},{n:"Lime wedges",a:"1 per glass"}],
    method:["Gently muddle the mint and lime in each glass.","Add sugar syrup and rum, then fill with crushed ice.","Top with soda water and stir.","Garnish with a mint sprig and lime."],
    tip:"Make a big batch of the rum-lime-syrup base; build with mint, ice and soda per glass." },
  { id:"gintonicbar", name:"Gin & Tonic Bar", emoji:"🍸", category:"cocktails", serves:"per glass", minGuests:6, glassware:"Large balloon/copa glasses", serveNote:"A help-yourself station — set out the botanicals",
    base300:[{n:"Gin",a:"50ml per glass"},{n:"Tonic water",a:"150ml per glass"},{n:"— BOTANICALS (set out):",a:""},{n:"Cucumber ribbons",a:"a bowl"},{n:"Lemon & lime wheels",a:"a bowl"},{n:"Fresh rosemary / mint",a:"a few sprigs"},{n:"Pink peppercorns / juniper",a:"a small dish"},{n:"Ice",a:"lots, big cubes"}],
    method:["Set out big glasses, ice and bowls of botanicals.","Pour a measure of gin over plenty of ice.","Top gently with tonic, pouring down a stirrer to keep the fizz.","Let guests add their own garnish."],
    tip:"Big ice cubes melt slower — buy or freeze large blocks for a proper G&T." },
  { id:"brandycoke", name:"Brandy & Coke", emoji:"🥃", category:"cocktails", serves:"per glass", minGuests:4, glassware:"Tumblers", serveNote:"The SA staple — keep it simple and ice cold",
    base300:[{n:"Brandy",a:"50ml per glass"},{n:"Cola",a:"150ml per glass"},{n:"Lemon wedge",a:"1 per glass"},{n:"Ice",a:"plenty"}],
    method:["Fill a tumbler with ice.","Pour over the brandy.","Top with cola.","Squeeze in a lemon wedge and drop it in."],
    tip:"A brandy-en-Coke needs nothing fancy — just keep everything ice cold." },
  { id:"cosmopolitan", name:"Cosmopolitan", emoji:"🍸", category:"cocktails", serves:"10", minGuests:8, glassware:"Martini/coupe glasses", serveNote:"Batch the mix; shake with ice to order",
    base300:[{n:"Vodka",a:"45ml per glass · 450ml per 10"},{n:"Triple sec / Cointreau",a:"15ml per glass · 150ml per 10"},{n:"Cranberry juice",a:"30ml per glass · 300ml per 10"},{n:"Fresh lime juice",a:"15ml per glass · 150ml per 10"},{n:"— GARNISH:",a:""},{n:"Lime wheel or orange twist",a:"1 per glass"}],
    method:["Mix the vodka, triple sec, cranberry and lime juice in a jug.","Chill the glasses.","Shake portions with ice and strain into the chilled glasses.","Garnish with a lime wheel or orange twist."],
    tip:"A clean pink colour means you've balanced it right — too red is too much cranberry." },
  { id:"strawberrydaiquiri", name:"Strawberry Daiquiri", emoji:"🍓", category:"cocktails", serves:"10", minGuests:8, glassware:"Coupe or hurricane glasses", serveNote:"Blend with ice for a frozen version",
    base300:[{n:"White rum",a:"45ml per glass · 450ml per 10"},{n:"Fresh strawberries",a:"3 per glass · 30 per 10"},{n:"Fresh lime juice",a:"20ml per glass · 200ml per 10"},{n:"Sugar syrup",a:"15ml per glass · 150ml per 10"},{n:"— GARNISH:",a:""},{n:"Strawberry or lime wheel",a:"1 per glass"}],
    method:["Blend the strawberries, rum, lime juice and sugar syrup until smooth.","For a frozen daiquiri, blend with a cup of ice.","Pour into chilled glasses.","Garnish with a strawberry."],
    tip:"Taste the strawberries first — sweeter berries need less syrup." },
  { id:"pinacolada", name:"Piña Colada", emoji:"🥥", category:"cocktails", serves:"10", minGuests:8, glassware:"Hurricane/tall glasses", serveNote:"Blend with ice — it's meant to be thick and frozen",
    base300:[{n:"White rum",a:"45ml per glass · 450ml per 10"},{n:"Coconut cream",a:"30ml per glass · 300ml per 10"},{n:"Pineapple juice",a:"90ml per glass · 900ml per 10"},{n:"— GARNISH:",a:""},{n:"Pineapple wedge",a:"1 per glass"},{n:"Maraschino cherry",a:"1 per glass"}],
    method:["Blend the rum, coconut cream, pineapple juice and a generous scoop of ice until thick and smooth.","Pour into tall glasses.","Garnish with a pineapple wedge and a cherry.","Serve with a straw."],
    tip:"Chill the pineapple juice first so you need less ice and the flavour stays strong." },
  { id:"espressomartini", name:"Espresso Martini", emoji:"☕", category:"cocktails", serves:"10", minGuests:8, glassware:"Martini glasses", serveNote:"Shake hard for that signature foam top",
    base300:[{n:"Vodka",a:"40ml per glass · 400ml per 10"},{n:"Coffee liqueur (Kahlua)",a:"20ml per glass · 200ml per 10"},{n:"Fresh espresso (cooled)",a:"30ml per glass · 300ml per 10"},{n:"Sugar syrup",a:"5ml per glass · 50ml per 10"},{n:"— GARNISH:",a:""},{n:"Coffee beans",a:"3 per glass"}],
    method:["Brew the espresso and cool it.","Mix the vodka, coffee liqueur, espresso and syrup in a jug.","Shake portions HARD with ice — the hard shake makes the foam.","Strain into chilled glasses and float 3 coffee beans on top."],
    tip:"Use fresh espresso, not instant — the crema is what gives the foam." },
  { id:"longisland", name:"Long Island Iced Tea", emoji:"🍹", category:"cocktails", serves:"8", minGuests:6, glassware:"Tall glasses", serveNote:"Strong — make it a special, not a free-pour",
    base300:[{n:"Vodka",a:"15ml per glass · 120ml per 8"},{n:"White rum",a:"15ml per glass · 120ml per 8"},{n:"Gin",a:"15ml per glass · 120ml per 8"},{n:"Tequila",a:"15ml per glass · 120ml per 8"},{n:"Triple sec",a:"15ml per glass · 120ml per 8"},{n:"Lemon juice",a:"20ml per glass · 160ml per 8"},{n:"Cola (to top)",a:"60ml per glass · 480ml per 8"},{n:"— GARNISH:",a:""},{n:"Lemon wedge",a:"1 per glass"}],
    method:["Mix the five spirits and lemon juice in a jug.","Pour over ice in tall glasses.","Top with a splash of cola for the iced-tea colour.","Garnish with a lemon wedge."],
    tip:"There's no actual tea in it — the cola just makes it look like iced tea. Strong stuff." },
  // ── SHOOTERS ──
  { id:"springbokkie", name:"Springbokkie", emoji:"🟢", category:"shooters", serves:"per shot", minGuests:4, glassware:"Shot glasses", serveNote:"The SA classic — green over cream, don't mix",
    base300:[{n:"Peppermint liqueur (green)",a:"15ml per shot"},{n:"Amarula cream",a:"15ml per shot"}],
    method:["Pour the peppermint liqueur into a shot glass first.","Gently layer the Amarula on top over the back of a spoon.","Serve in its layers — green on the bottom, cream on top.","Down in one."],
    tip:"Green-and-cream like the Springbok jersey — that's where the name comes from." },
  { id:"melktertjie", name:"Melktertjie", emoji:"🥧", category:"shooters", serves:"per shot", minGuests:4, glassware:"Shot glasses", serveNote:"Tastes exactly like milk tart",
    base300:[{n:"Cream liqueur (Amarula/Baileys)",a:"20ml per shot"},{n:"Vanilla or cake vodka",a:"10ml per shot"},{n:"— TOP:",a:""},{n:"Cinnamon",a:"a dusting"}],
    method:["Mix the cream liqueur and vanilla vodka.","Pour into a shot glass.","Dust the top with cinnamon.","Serve cold."],
    tip:"A pinch of cinnamon on top is what makes it taste like a real melktert." },
  { id:"applepie", name:"Apple Pie Shooter", emoji:"🍎", category:"shooters", serves:"per shot", minGuests:4, glassware:"Shot glasses", serveNote:"Warm-spiced and sweet",
    base300:[{n:"Spiced rum or cinnamon liqueur",a:"15ml per shot"},{n:"Apple juice",a:"15ml per shot"},{n:"— TOP:",a:""},{n:"Whipped cream",a:"a swirl"},{n:"Cinnamon",a:"a dusting"}],
    method:["Mix the spiced rum and apple juice.","Pour into a shot glass.","Top with a little whipped cream.","Dust with cinnamon."],
    tip:"Tastes like apple pie in a glass — a crowd-pleaser at winter parties." },
  { id:"jellyshots", name:"Jelly Shots", emoji:"🍮", category:"shooters", serves:"20", minGuests:10, glassware:"Small cups / shot glasses", serveNote:"Make a day ahead — they need to set",
    base300:[{n:"Jelly (any flavour)",a:"1 packet per 8 shots · 2.5 packets per 20"},{n:"Boiling water",a:"as per jelly packet"},{n:"Vodka",a:"15ml per shot · 300ml per 20"},{n:"— OPTIONAL:",a:""},{n:"Cold water",a:"to replace some of the vodka for milder shots"}],
    method:["Make the jelly with boiling water as per the packet, but use less cold water.","Once cooled slightly, stir in the vodka.","Pour into small cups or shot glasses.","Chill until fully set, at least 4 hours."],
    tip:"Replace the cold water with vodka, not extra — too much alcohol stops the jelly setting." },
  { id:"tequilaslammer", name:"Tequila (Salt & Lime)", emoji:"🍋", category:"shooters", serves:"per shot", minGuests:4, glassware:"Shot glasses", serveNote:"Lick, sip, suck — the proper way",
    base300:[{n:"Tequila",a:"30ml per shot"},{n:"— WITH:",a:""},{n:"Salt",a:"for the hand"},{n:"Lime wedge",a:"1 per shot"}],
    method:["Pour a measure of tequila into a shot glass.","Lick the back of your hand and shake on a little salt.","Lick the salt, down the tequila.","Bite the lime wedge straight after."],
    tip:"A good silver tequila is smooth enough to sip — save the slamming for the cheap stuff." },
  { id:"choccake", name:"Chocolate Cake Shooter", emoji:"🍫", category:"shooters", serves:"per shot", minGuests:4, glassware:"Shot glasses", serveNote:"No chocolate in it — but it tastes like it",
    base300:[{n:"Vanilla vodka",a:"15ml per shot"},{n:"Hazelnut liqueur (Frangelico)",a:"15ml per shot"},{n:"— WITH:",a:""},{n:"Lemon wedge",a:"1 per shot"},{n:"Sugar",a:"to coat the lemon"}],
    method:["Mix the vanilla vodka and hazelnut liqueur in a shot glass.","Coat a lemon wedge in sugar.","Down the shot.","Bite the sugared lemon straight after — that's the magic."],
    tip:"The sugared lemon is the trick — it makes the whole thing taste like chocolate cake." },
  // ── MOCKTAILS & SOFT ──
  { id:"virginmojito", name:"Virgin Mojito", emoji:"🌿", category:"mocktails", serves:"10", minGuests:6, glassware:"Highball glasses", serveNote:"All the fresh-mint lift, zero alcohol",
    base300:[{n:"Fresh lime juice",a:"25ml per glass · 250ml per 10"},{n:"Sugar syrup",a:"15ml per glass · 150ml per 10"},{n:"Soda water",a:"180ml per glass · 1.8L per 10"},{n:"— GARNISH:",a:""},{n:"Fresh mint",a:"6 leaves per glass"},{n:"Lime wedges",a:"1 per glass"}],
    method:["Muddle the mint and lime gently in the glass.","Add sugar syrup and fill with crushed ice.","Top with soda water and stir.","Garnish with mint and lime."],
    tip:"A splash of apple juice adds body and makes it feel more grown-up." },
  { id:"shirleytemple", name:"Shirley Temple", emoji:"🍒", category:"mocktails", serves:"per glass", minGuests:4, glassware:"Tall glasses", serveNote:"The kids'-party classic",
    base300:[{n:"Lemonade (Sprite/7-Up)",a:"200ml per glass"},{n:"Grenadine",a:"15ml per glass"},{n:"Maraschino cherry",a:"1 per glass"},{n:"Ice",a:"plenty"}],
    method:["Fill a glass with ice.","Pour over the lemonade.","Drizzle in the grenadine so it sinks to the bottom.","Top with a cherry."],
    tip:"Let the grenadine settle for a pretty pink-to-clear gradient." },
  { id:"berryspritzer", name:"Berry Spritzer", emoji:"🫐", category:"mocktails", serves:"10", minGuests:6, glassware:"Wine glasses", serveNote:"Pretty, light and not too sweet",
    base300:[{n:"Mixed berry juice / cordial",a:"60ml per glass · 600ml per 10"},{n:"Sparkling water",a:"140ml per glass · 1.4L per 10"},{n:"— GARNISH:",a:""},{n:"Fresh or frozen berries",a:"a few per glass"},{n:"Fresh mint",a:"a sprig per glass"}],
    method:["Pour the berry juice over ice.","Top with sparkling water.","Drop in a few berries and a mint sprig.","Stir gently."],
    tip:"Frozen berries double as edible ice cubes that won't dilute the drink." },
  { id:"lemonade", name:"Homemade Lemonade", emoji:"🍋", category:"mocktails", serves:"10–12", minGuests:8, glassware:"Jug + tumblers", serveNote:"Make the syrup ahead; mix with water to order",
    base300:[{n:"Lemon juice (fresh)",a:"30ml per glass · 360ml per 12"},{n:"Sugar",a:"20g per glass · 240g per 12"},{n:"Water",a:"170ml per glass · 2L per 12"},{n:"— GARNISH:",a:""},{n:"Lemon slices",a:"a few per jug"},{n:"Fresh mint",a:"a handful"}],
    method:["Make a syrup: dissolve the sugar in an equal amount of hot water, then cool.","Mix the lemon juice, syrup and cold water in a jug.","Taste and balance the sweet/sour with more syrup or lemon.","Serve over ice with lemon slices and mint."],
    tip:"Add a handful of crushed raspberries or a few sprigs of rosemary for a twist." },
  { id:"virginpinacolada", name:"Virgin Piña Colada", emoji:"🥥", category:"mocktails", serves:"10", minGuests:6, glassware:"Hurricane/tall glasses", serveNote:"All the tropical, none of the rum",
    base300:[{n:"Coconut cream",a:"30ml per glass · 300ml per 10"},{n:"Pineapple juice",a:"120ml per glass · 1.2L per 10"},{n:"— GARNISH:",a:""},{n:"Pineapple wedge",a:"1 per glass"},{n:"Maraschino cherry",a:"1 per glass"}],
    method:["Blend the coconut cream and pineapple juice with a scoop of ice until thick.","Pour into tall glasses.","Garnish with a pineapple wedge and a cherry.","Serve with a straw."],
    tip:"Add a frozen banana to the blender for an even thicker, creamier version." },
  { id:"granadillacooler", name:"Granadilla Cooler", emoji:"🟡", category:"mocktails", serves:"10", minGuests:6, glassware:"Tall glasses", serveNote:"Sweet-tart and very South African",
    base300:[{n:"Granadilla pulp or cordial",a:"40ml per glass · 400ml per 10"},{n:"Lemonade or sparkling water",a:"160ml per glass · 1.6L per 10"},{n:"— GARNISH:",a:""},{n:"Fresh granadilla pulp",a:"a spoon per glass"},{n:"Fresh mint",a:"a sprig per glass"}],
    method:["Spoon the granadilla pulp or cordial into each glass over ice.","Top with lemonade or sparkling water.","Stir gently.","Finish with a spoon of fresh pulp and a mint sprig."],
    tip:"Fresh granadilla pips on top look beautiful and add a lovely crunch." },
  // ── HOMEMADE & CREAM ──
  { id:"homemadebaileys", name:"Homemade Baileys", emoji:"🥛", category:"homemade", serves:"15–20", minGuests:1, glassware:"Bottle → small glasses", serveNote:"Keeps 2 weeks in the fridge — make ahead",
    base300:[{n:"Fresh cream",a:"250ml per batch"},{n:"Condensed milk",a:"1 tin (385g) per batch"},{n:"Whisky or brandy",a:"250ml per batch"},{n:"Strong coffee (cooled)",a:"15ml per batch"},{n:"Cocoa powder",a:"5g per batch"},{n:"Vanilla essence",a:"5ml per batch"}],
    method:["Blend the cream, condensed milk, whisky, coffee, cocoa and vanilla until smooth.","Pour into a clean glass bottle.","Chill — it's ready to drink, but better after a day.","Shake before serving over ice."],
    tip:"Keeps about 2 weeks refrigerated. Shake well each time before pouring." },
  { id:"dompedro", name:"Dom Pedro", emoji:"🥃", category:"homemade", serves:"per glass", minGuests:1, glassware:"Wine glass + straw", serveNote:"The SA after-dinner classic — its own moment",
    base300:[{n:"Vanilla ice cream",a:"2 scoops per glass"},{n:"Cream",a:"30ml per glass"},{n:"Whisky / Kahlua / Amarula / peppermint",a:"30ml per glass"},{n:"— TOP:",a:""},{n:"Grated chocolate or a flake",a:"to finish"}],
    method:["Blend the ice cream, cream and your chosen liqueur until just smooth — don't over-blend.","Pour into a wine glass.","Top with grated chocolate or a flake.","Serve with a straw and a spoon."],
    tip:"Whisky is the classic; Kahlua, Amarula and peppermint are the favourite variations — offer a few." },
  { id:"advocaat", name:"Advocaat (Egg Liqueur)", emoji:"🟡", category:"homemade", serves:"12–15", minGuests:1, glassware:"Bottle → small glasses", serveNote:"Rich Dutch egg liqueur — a little goes far",
    base300:[{n:"Egg yolks",a:"6 per batch"},{n:"Condensed milk",a:"1 tin (385g) per batch"},{n:"Brandy",a:"200ml per batch"},{n:"Vanilla essence",a:"5ml per batch"},{n:"— TOP:",a:""},{n:"Nutmeg",a:"a grating"}],
    method:["Whisk the egg yolks and condensed milk until pale and thick.","Slowly whisk in the brandy and vanilla.","Pour into a clean bottle and chill.","Serve in small glasses with a grating of nutmeg."],
    tip:"Use the freshest eggs you can. Serve thick and cold in small measures." },
  { id:"eggnog", name:"Egg Nog", emoji:"🥚", category:"homemade", serves:"10–12", minGuests:1, glassware:"Cups / small glasses", serveNote:"A festive favourite — alcoholic or not",
    base300:[{n:"Milk",a:"100ml per glass · 1.2L per 12"},{n:"Cream",a:"20ml per glass · 240ml per 12"},{n:"Egg yolks",a:"0.5 per glass · 6 per 12"},{n:"Sugar",a:"10g per glass · 120g per 12"},{n:"Brandy or rum (optional)",a:"15ml per glass · 180ml per 12"},{n:"— TOP:",a:""},{n:"Nutmeg & cinnamon",a:"a dusting"}],
    method:["Whisk the egg yolks and sugar until pale.","Warm the milk and cream gently, then whisk into the yolks.","Cook gently until slightly thickened — do not boil.","Cool, stir in the brandy or rum if using, and serve dusted with nutmeg."],
    tip:"Leave out the alcohol and it's a lovely festive drink for the whole family." },
  { id:"homemadekahlua", name:"Homemade Coffee Liqueur", emoji:"☕", category:"homemade", serves:"15–20", minGuests:1, glassware:"Bottle → small glasses", serveNote:"A homemade Kahlua — great in coffee or Dom Pedros",
    base300:[{n:"Strong coffee / espresso",a:"250ml per batch"},{n:"Sugar",a:"300g per batch"},{n:"Water",a:"250ml per batch"},{n:"Vodka or brandy",a:"350ml per batch"},{n:"Vanilla essence",a:"10ml per batch"}],
    method:["Dissolve the sugar in the hot coffee and water to make a syrup, then cool.","Stir in the vodka or brandy and vanilla.","Pour into a clean bottle.","Rest a few days for the flavour to round out, then use in coffee, Dom Pedros or over ice."],
    tip:"It only gets better with a week or two in the bottle — make a big batch ahead of the season." },
  { id:"thickmilkshake", name:"Thick Milkshake", emoji:"🥤", category:"homemade", serves:"per glass", minGuests:1, glassware:"Tall glass + straw", serveNote:"Diner-thick — for the kids' table or a treat",
    base300:[{n:"Vanilla ice cream",a:"2 scoops per glass"},{n:"Milk",a:"120ml per glass"},{n:"Flavour (chocolate/strawberry/caramel)",a:"30ml per glass"},{n:"— TOP:",a:""},{n:"Whipped cream",a:"a swirl"},{n:"Sprinkles or a flake",a:"to finish"}],
    method:["Blend the ice cream, milk and flavour until thick and smooth.","Pour into a tall glass.","Top with whipped cream.","Finish with sprinkles or a flake and serve with a fat straw."],
    tip:"Less milk = thicker shake. Add a scoop more ice cream if it's too runny." },
  // ── HOT DRINKS ──
  { id:"filtercoffee", name:"Filter Coffee Urn", emoji:"☕", category:"hot", serves:"20", minGuests:15, glassware:"Urn + cups", serveNote:"Brew fresh; keep the urn on low, never boiling",
    base300:[{n:"Ground filter coffee",a:"7g per cup · 140g per 20"},{n:"Water",a:"180ml per cup · 3.6L per 20"},{n:"— ON THE SIDE:",a:""},{n:"Milk",a:"30ml per cup · 600ml per 20"},{n:"Sugar",a:"5g per cup · 100g per 20"}],
    method:["Use 1 heaped tablespoon of coffee per 2 cups of water.","Brew in a filter machine or urn.","Keep warm on low — do not let it boil or it turns bitter.","Set out milk, sugar and cups for self-service."],
    tip:"For a crowd, a 20-cup urn plus a jug of hot milk beats making cups one by one." },
  { id:"teastation", name:"Tea Station", emoji:"🫖", category:"hot", serves:"20", minGuests:15, glassware:"Urn + cups", serveNote:"Offer black, rooibos and a herbal option",
    base300:[{n:"Tea bags (black + rooibos)",a:"1 per cup · 20 per 20"},{n:"Boiling water",a:"180ml per cup · 3.6L per 20"},{n:"— ON THE SIDE:",a:""},{n:"Milk",a:"30ml per cup · 600ml per 20"},{n:"Sugar",a:"5g per cup · 100g per 20"},{n:"Lemon slices",a:"a few"}],
    method:["Keep a hot-water urn at a rolling temperature.","Set out black tea, rooibos and herbal options in labelled tins.","Provide milk, sugar, honey and lemon.","Let guests help themselves."],
    tip:"Rooibos is caffeine-free and a crowd favourite — always include it." },
  { id:"hotchocolate", name:"Hot Chocolate", emoji:"☕", category:"hot", serves:"10", minGuests:6, glassware:"Mugs", serveNote:"Real chocolate beats powder — melt it in",
    base300:[{n:"Full cream milk",a:"200ml per mug · 2L per 10"},{n:"Dark chocolate (chopped)",a:"30g per mug · 300g per 10"},{n:"Cocoa powder",a:"5g per mug · 50g per 10"},{n:"Sugar",a:"8g per mug · 80g per 10"},{n:"— TOP:",a:""},{n:"Cream or marshmallows",a:"to finish"}],
    method:["Heat the milk gently — don't boil.","Whisk in the chopped chocolate, cocoa and sugar until smooth.","Keep warm on low heat.","Serve in mugs topped with cream or marshmallows."],
    tip:"A pinch of cinnamon or chilli turns it into a grown-up winter warmer." },
  { id:"gluhwein", name:"Glühwein (Mulled Wine)", emoji:"🍷", category:"hot", serves:"10", minGuests:8, glassware:"Heatproof glasses/mugs", serveNote:"Warm gently — never boil, or the alcohol cooks off",
    base300:[{n:"Red wine",a:"150ml per glass · 1.5L per 10"},{n:"Orange (sliced)",a:"1 per batch"},{n:"Sugar or honey",a:"10g per glass · 100g per 10"},{n:"Cinnamon sticks",a:"2 per batch"},{n:"Cloves",a:"4 per batch"},{n:"Star anise",a:"2 per batch"}],
    method:["Warm the wine gently with the orange, sugar and spices.","Keep below a simmer for 15–20 min so it infuses but doesn't boil.","Taste and adjust the sweetness.","Ladle into heatproof glasses, avoiding the whole spices."],
    tip:"A splash of brandy at the end adds warmth without cooking off the alcohol." },
  { id:"irishcoffee", name:"Irish Coffee", emoji:"☘️", category:"hot", serves:"per glass", minGuests:1, glassware:"Heatproof glasses", serveNote:"Float the cream — don't stir it in",
    base300:[{n:"Hot strong coffee",a:"150ml per glass"},{n:"Irish whiskey",a:"30ml per glass"},{n:"Brown sugar",a:"1 tsp per glass"},{n:"— TOP:",a:""},{n:"Lightly whipped cream",a:"a float"}],
    method:["Stir the sugar into the hot coffee until dissolved.","Add the whiskey.","Lightly whip the cream so it's pourable but holds.","Float the cream over the back of a spoon and drink the hot coffee through the cool cream."],
    tip:"Don't stir once the cream is on — hot coffee through cool cream is the whole point." },
  { id:"masalachai", name:"Masala Chai", emoji:"🫖", category:"hot", serves:"10", minGuests:6, glassware:"Cups", serveNote:"Indian spiced milk tea — simmer, don't rush",
    base300:[{n:"Water",a:"100ml per cup · 1L per 10"},{n:"Milk",a:"100ml per cup · 1L per 10"},{n:"Black tea (loose or bags)",a:"1 tsp per cup · 10 tsp per 10"},{n:"Sugar",a:"8g per cup · 80g per 10"},{n:"— SPICES:",a:""},{n:"Fresh ginger, cardamom, cinnamon, cloves",a:"to taste"}],
    method:["Simmer the water with the bruised spices and ginger for 5 min.","Add the tea and simmer 2 min more.","Pour in the milk and sugar and bring back to a gentle simmer.","Strain into cups and serve hot."],
    tip:"Bruise the cardamom and ginger so they release their oils — that's the whole flavour." },
  { id:"moroccanmint", name:"Moroccan Mint Tea", emoji:"🌿", category:"hot", serves:"10", minGuests:6, glassware:"Glasses", serveNote:"Pour from a height for the traditional froth",
    base300:[{n:"Green tea (gunpowder)",a:"1 tsp per 2 glasses · 5 tsp per 10"},{n:"Boiling water",a:"150ml per glass · 1.5L per 10"},{n:"Fresh mint",a:"a big handful"},{n:"Sugar",a:"10g per glass · 100g per 10"}],
    method:["Steep the green tea in boiling water 3–4 min.","Add a generous handful of fresh mint and the sugar.","Steep a few minutes more.","Pour from a height into glasses to make it froth."],
    tip:"Lots of fresh mint and quite sweet is the traditional way — pour high for the foam." },
  { id:"cafeconleche", name:"Café con Leche", emoji:"☕", category:"hot", serves:"10", minGuests:6, glassware:"Cups", serveNote:"Equal parts strong coffee and hot milk",
    base300:[{n:"Strong coffee / espresso",a:"100ml per cup · 1L per 10"},{n:"Hot milk",a:"100ml per cup · 1L per 10"},{n:"Sugar",a:"5g per cup · 50g per 10"}],
    method:["Brew strong coffee or espresso.","Heat the milk until hot but not boiling.","Pour equal parts coffee and hot milk into each cup.","Sweeten to taste."],
    tip:"Froth the milk a little for a café feel — and use a good dark roast." },
  { id:"hottoddy", name:"Hot Toddy", emoji:"🍋", category:"hot", serves:"per glass", minGuests:1, glassware:"Heatproof glasses", serveNote:"The classic winter comfort — and cold-cure",
    base300:[{n:"Whisky or brandy",a:"30ml per glass"},{n:"Hot water",a:"150ml per glass"},{n:"Honey",a:"1 tbsp per glass"},{n:"Lemon juice",a:"15ml per glass"},{n:"— GARNISH:",a:""},{n:"Lemon slice & cinnamon stick",a:"1 each per glass"}],
    method:["Stir the honey and lemon juice into the hot water until the honey dissolves.","Add the whisky or brandy.","Drop in a lemon slice and a cinnamon stick.","Serve steaming hot."],
    tip:"More honey and lemon, less booze, makes a soothing cold-and-flu version." },
  { id:"amarulahotchoc", name:"Amarula Hot Chocolate", emoji:"🍫", category:"hot", serves:"10", minGuests:6, glassware:"Mugs", serveNote:"Grown-up hot chocolate with an SA twist",
    base300:[{n:"Full cream milk",a:"180ml per mug · 1.8L per 10"},{n:"Dark chocolate (chopped)",a:"30g per mug · 300g per 10"},{n:"Amarula cream",a:"30ml per mug · 300ml per 10"},{n:"Sugar",a:"5g per mug · 50g per 10"},{n:"— TOP:",a:""},{n:"Whipped cream & a flake",a:"to finish"}],
    method:["Heat the milk gently and whisk in the chopped chocolate and sugar until smooth.","Stir in the Amarula off the heat.","Pour into mugs.","Top with whipped cream and a flake."],
    tip:"Stir the Amarula in at the end so the alcohol stays — don't let it boil." },
  // ── WELCOME & BUBBLY ──
  { id:"sparklingwelcome", name:"Sparkling Welcome", emoji:"🥂", category:"bubbly", serves:"6 per bottle", minGuests:10, glassware:"Flutes/coupes", serveNote:"Keep on ice; pour just before guests arrive",
    base300:[{n:"MCC / sparkling wine",a:"120ml per glass · 1 bottle per 6"},{n:"— OPTIONAL:",a:""},{n:"Fresh berry or twist of lemon",a:"1 per glass"}],
    method:["Chill the bottles thoroughly on ice.","Pour just before guests arrive so it stays fizzy.","Tilt the glass and pour gently down the side.","Drop in a berry or lemon twist if you like."],
    tip:"One bottle pours about 6 flutes — count 1–2 welcome glasses per guest." },
  { id:"mimosa", name:"Mimosa", emoji:"🍊", category:"bubbly", serves:"8", minGuests:8, glassware:"Flutes", serveNote:"Half bubbly, half juice — add the fizz last",
    base300:[{n:"MCC / sparkling wine",a:"75ml per glass · 600ml per 8"},{n:"Fresh orange juice",a:"75ml per glass · 600ml per 8"},{n:"— GARNISH:",a:""},{n:"Orange twist",a:"1 per glass"}],
    method:["Chill both the bubbly and the orange juice.","Half-fill each flute with orange juice.","Top gently with sparkling wine.","Finish with an orange twist."],
    tip:"Use freshly squeezed juice — it's the difference between nice and special." },
  { id:"sparklinggrape", name:"Sparkling Grape (Non-Alc Toast)", emoji:"🥂", category:"bubbly", serves:"6 per bottle", minGuests:6, glassware:"Flutes", serveNote:"The all-ages toast — kids and drivers included",
    base300:[{n:"Sparkling grape juice",a:"120ml per glass · 1 bottle per 6"},{n:"— OPTIONAL:",a:""},{n:"Fresh berry",a:"1 per glass"}],
    method:["Chill the bottles well.","Pour into flutes just before the toast.","Drop in a berry for colour.","Serve immediately so it stays sparkling."],
    tip:"Always have a non-alcoholic toast option — kids, drivers and non-drinkers included." },
  { id:"bellini", name:"Bellini", emoji:"🍑", category:"bubbly", serves:"8", minGuests:8, glassware:"Flutes", serveNote:"Peach purée + bubbly — add the fizz last",
    base300:[{n:"MCC / sparkling wine",a:"100ml per glass · 800ml per 8"},{n:"Peach purée",a:"40ml per glass · 320ml per 8"},{n:"— GARNISH:",a:""},{n:"Peach slice",a:"1 per glass"}],
    method:["Spoon the peach purée into each chilled flute.","Top gently with sparkling wine.","Stir very lightly.","Garnish with a thin peach slice."],
    tip:"Use ripe white peaches blended smooth — tinned peaches work in a pinch." },
  { id:"kirroyale", name:"Kir Royale", emoji:"🍇", category:"bubbly", serves:"8", minGuests:8, glassware:"Flutes", serveNote:"A splash of blackcurrant under the bubbly",
    base300:[{n:"MCC / sparkling wine",a:"120ml per glass · 960ml per 8"},{n:"Crème de cassis (blackcurrant)",a:"10ml per glass · 80ml per 8"},{n:"— GARNISH:",a:""},{n:"Fresh blackberry or raspberry",a:"1 per glass"}],
    method:["Pour a splash of crème de cassis into each chilled flute.","Top gently with sparkling wine.","Don't stir — let it blush up from the bottom.","Drop in a berry."],
    tip:"A little cassis goes a long way — it should tint the bubbly, not overpower it." },
];
