function set(upd){ Object.assign(S,upd); draw(); }

function setQuiet(upd){
  const root=document.getElementById("root");
  if(root) root._savedScroll = window.scrollY;
  Object.assign(S,upd);
  draw();
}

const POPULAR_RECIPES = {
  sa:[
    { id:"pr_bobotie", name:"Bobotie", intl:"Spiced Mince Bake", emoji:"🍛", cuisine:"South African", time:75, serves:6,
      tags:["cape malay","mince","curry","bakes","dinner"],
      ingredients:[
        {n:"Beef or lamb mince",pp:150,u:"g"},
        {n:"Onion (finely diced)",pp:25,u:"g"},
        {n:"Garlic (minced)",pp:3,u:"g"},
        {n:"Curry powder",pp:3,u:"g"},
        {n:"Turmeric",pp:1,u:"g"},
        {n:"Apricot jam",pp:15,u:"g"},
        {n:"Chutney (fruit chutney)",pp:15,u:"g"},
        {n:"White bread (soaked in milk)",pp:30,u:"g"},
        {n:"Milk (for soaking bread)",pp:30,u:"ml"},
        {n:"Egg",pp:0.3,u:"egg"},
        {n:"Lemon juice",pp:5,u:"ml"},
        {n:"Raisins",pp:15,u:"g"},
        {n:"Almonds (flaked)",pp:10,u:"g"},
        {n:"Bay leaves",pp:null,u:""},
        {n:"Eggs (for topping)",pp:0.5,u:"egg"},
        {n:"Milk (for topping)",pp:30,u:"ml"},
        {n:"Turmeric (for topping)",pp:0.5,u:"g"},
      ],
      method:["Preheat oven to 180°C.","Sauté onion and garlic until soft. Add curry powder and turmeric, cook 1 min.","Add mince. Brown completely — no pink remaining.","Add jam, chutney, lemon juice and raisins. Mix well.","Squeeze bread dry and crumble into mince. Mix. Season well.","Spoon into greased baking dish. Press bay leaves on top.","Beat eggs with milk and turmeric. Pour over the mince.","Bake 35–40 min until topping is set and golden.","Remove bay leaves before serving. Serve with yellow rice and chutney."],
      tip:"The bread is what makes Bobotie uniquely South African — it absorbs the spices and gives the dish its characteristic moist texture. Don't skip the apricot jam — it's the secret sweetness that balances the curry.",
      howItFeels:"The smell of this in the oven is childhood, Sunday afternoons and someone's ouma.",
      storage:"Fridge 3 days. Freezes well without the egg topping." },

    { id:"pr_malvapudding", name:"Malva Pudding", intl:"SA Sticky Toffee Pudding", emoji:"🍮", cuisine:"South African", time:60, serves:8,
      tags:["dessert","bakes","sweet","classic","pudding"],
      ingredients:[
        {n:"Sugar",pp:30,u:"g"},
        {n:"Egg",pp:0.25,u:"egg"},
        {n:"Apricot jam",pp:15,u:"g"},
        {n:"Butter (melted)",pp:8,u:"g"},
        {n:"Cake flour",pp:30,u:"g"},
        {n:"Bicarbonate of soda",pp:0.5,u:"g"},
        {n:"Vinegar",pp:3,u:"ml"},
        {n:"Milk",pp:30,u:"ml"},
        {n:"Cream",pp:45,u:"ml"},
        {n:"Butter (for sauce)",pp:15,u:"g"},
        {n:"Sugar (for sauce)",pp:20,u:"g"},
        {n:"Hot water",pp:15,u:"ml"},
        {n:"Vanilla essence",pp:1,u:"ml"},
      ],
      method:["Preheat oven to 180°C. Grease a baking dish well.","Beat sugar and egg until pale and fluffy — about 3 min.","Add jam, melted butter, vinegar and milk. Mix well.","Sift flour and bicarb together. Fold into wet mixture.","Pour into greased dish. Bake 30–35 min until deep golden brown and a skewer comes out clean.","SAUCE: Combine cream, butter, sugar, hot water and vanilla in a small pot. Heat until butter melts and sugar dissolves — do not boil.","While pudding is still hot and fresh from the oven, poke holes all over with a skewer.","Pour ALL the warm sauce over the hot pudding. It will absorb completely — don't panic.","Serve immediately with extra cream or vanilla ice cream."],
      tip:"The sauce must go on while the pudding is HOT — this is non-negotiable. Cold pudding won't absorb the sauce.",
      howItFeels:"Warm, sweet, sticky — like being wrapped in a hug at a winter braai.",
      storage:"Fridge 3 days. Reheat in microwave with a splash of cream." },

    { id:"pr_koeksisters", name:"Koeksisters", intl:"Syrup-Glazed Plaited Pastry", emoji:"🍩", cuisine:"South African", time:90, serves:12,
      tags:["dessert","sweet","fried","afrikaner","syrup"],
      ingredients:[
        {n:"Cake flour",pp:25,u:"g"},
        {n:"Baking powder",pp:0.5,u:"g"},
        {n:"Salt",pp:0.2,u:"g"},
        {n:"Butter (cold)",pp:4,u:"g"},
        {n:"Egg",pp:0.1,u:"egg"},
        {n:"Milk",pp:15,u:"ml"},
        {n:"Oil (for deep frying)",pp:null,u:""},
        {n:"Sugar (for syrup)",pp:50,u:"g"},
        {n:"Water (for syrup)",pp:25,u:"ml"},
        {n:"Cream of tartar",pp:0.2,u:"g"},
        {n:"Lemon juice",pp:2,u:"ml"},
      ],
      method:["SYRUP (make the day before — must be ice cold): Dissolve sugar in water over low heat. Add cream of tartar and lemon juice. Boil 10 min. Cool completely. Refrigerate overnight.","Sift flour, baking powder and salt. Rub in cold butter until breadcrumb texture.","Add egg and milk. Mix to a soft dough. Rest 10 min.","Roll out 5mm thick. Cut into 8cm × 2cm strips. Cut each strip almost through lengthways. Plait.","Heat oil to 180°C. Fry in batches until golden brown — about 3 min.","IMMEDIATELY drop hot koeksisters into the ice-cold syrup. Remove after 30 seconds. Place on wire rack."],
      tip:"Syrup must be ice cold — put it in the freezer 30 min before frying. They go straight from hot oil into cold syrup. The thermal shock creates that signature crispy-sticky texture.",
      howItFeels:"Sticky fingers and sugar-rush — the original SA street food.",
      storage:"Room temperature 3 days. Do not refrigerate — they go soggy." },

    { id:"pr_frikkadels", name:"Frikkadels", intl:"SA Beef Meatballs", emoji:"🍖", cuisine:"South African", time:40, serves:4,
      tags:["mince","meatballs","dinner","afrikaner","family"],
      ingredients:[
        {n:"Beef mince",pp:125,u:"g"},
        {n:"Onion (very finely grated)",pp:20,u:"g"},
        {n:"White bread (crusts removed, soaked in milk)",pp:25,u:"g"},
        {n:"Milk (for soaking)",pp:30,u:"ml"},
        {n:"Egg",pp:0.25,u:"egg"},
        {n:"Worcestershire sauce",pp:3,u:"ml"},
        {n:"Fresh parsley (finely chopped)",pp:5,u:"g"},
        {n:"Salt and pepper",pp:null,u:""},
        {n:"Oil or butter (for frying)",pp:10,u:"ml"},
      ],
      method:["Squeeze bread dry. Combine all ingredients except oil. Mix well — hands are best.","Shape into slightly flattened balls — about 4cm diameter.","Heat oil in pan over medium heat. Fry in batches — don't crowd the pan.","Fry 4 min per side until deep golden brown and cooked through.","Rest 5 min before serving."],
      tip:"Grated onion rather than diced — it disappears into the meat and adds moisture without chunks. Soaked bread is what makes frikkadels light rather than dense.",
      howItFeels:"Every SA home has a frikkadel memory. This is that memory.",
      storage:"Fridge 3 days. Freezer 2 months." },

    { id:"pr_vetkoek", name:"Vetkoek with Mince", intl:"Fried Dough Bread with Mince", emoji:"🍞", cuisine:"South African", time:60, serves:6,
      tags:["bread","fried","mince","street food","afrikaner"],
      ingredients:[
        {n:"Bread flour",pp:60,u:"g"},
        {n:"Instant yeast",pp:1,u:"g"},
        {n:"Salt",pp:0.5,u:"g"},
        {n:"Sugar",pp:2,u:"g"},
        {n:"Lukewarm water",pp:40,u:"ml"},
        {n:"Oil for deep frying",pp:null,u:""},
        {n:"Beef mince",pp:60,u:"g"},
        {n:"Onion (diced)",pp:15,u:"g"},
        {n:"Tomato (diced)",pp:20,u:"g"},
        {n:"Curry powder",pp:1,u:"g"},
        {n:"Salt and pepper",pp:null,u:""},
      ],
      method:["Mix flour, yeast, salt and sugar. Add water gradually — mix to a soft dough.","Knead 8 min until smooth. Cover and prove 1 hour until doubled.","MINCE: Fry onion until soft. Add mince, brown completely. Add tomato and curry powder. Simmer 10 min. Season well.","Knock dough back. Divide into balls (about 70g each). Flatten slightly.","Heat oil to 170°C. Fry vetkoek in batches, 4–5 min per side until deep golden brown.","Split open immediately and fill with curry mince."],
      tip:"Oil temperature is critical — too hot and they're raw inside, too cool and they're greasy. Test with a small piece of dough first.",
      howItFeels:"Sommer standing by the stall, vetkoek in hand, watching the world go by.",
      storage:"Vetkoek best eaten fresh. Mince fridge 3 days." },

    { id:"pr_sosaties", name:"Sosaties", intl:"Cape Malay Skewers", emoji:"🍢", cuisine:"South African", time:240, serves:6,
      tags:["braai","skewer","cape malay","lamb","marinade"],
      ingredients:[
        {n:"Lamb (shoulder or leg, cubed 3cm)",pp:150,u:"g"},
        {n:"Dried apricots",pp:15,u:"g"},
        {n:"Onion (cut in wedges)",pp:20,u:"g"},
        {n:"Onion (finely diced — for marinade)",pp:15,u:"g"},
        {n:"Garlic",pp:2,u:"g"},
        {n:"Curry powder",pp:3,u:"g"},
        {n:"Turmeric",pp:0.5,u:"g"},
        {n:"Apricot jam",pp:20,u:"g"},
        {n:"White wine vinegar",pp:10,u:"ml"},
        {n:"Bay leaves",pp:null,u:""},
        {n:"Oil",pp:5,u:"ml"},
      ],
      method:["MARINADE: Fry onion and garlic in oil until soft. Add curry powder and turmeric — cook 1 min. Add jam and vinegar. Cool completely.","Combine lamb cubes with marinade. Add bay leaves. Marinate minimum 4 hours — overnight is best.","Thread lamb onto skewers alternating with dried apricots and onion wedges.","Braai over medium-hot coals — about 12–15 min, turning regularly.","Baste with remaining marinade while cooking.","Rest 5 min before serving."],
      tip:"Overnight marinating is worth it — the apricot jam tenderises the lamb. Don't grill too hot — the jam burns easily.",
      howItFeels:"Cape Malay heritage on a stick — smoke, spice, sweetness.",
      storage:"Raw marinated meat fridge 2 days. Cooked 3 days." },

    { id:"pr_potjiekos", name:"Potjiekos — Lamb Neck", intl:"SA Slow-Cooked Pot Stew", emoji:"🥘", cuisine:"South African", time:180, serves:6,
      tags:["potjie","braai","slow cook","lamb","stew"],
      ingredients:[
        {n:"Lamb neck pieces",pp:200,u:"g"},
        {n:"Onion (roughly chopped)",pp:25,u:"g"},
        {n:"Garlic (minced)",pp:3,u:"g"},
        {n:"Carrots (cut in chunks)",pp:30,u:"g"},
        {n:"Potatoes (quartered)",pp:60,u:"g"},
        {n:"Butternut (cubed)",pp:40,u:"g"},
        {n:"Green beans",pp:20,u:"g"},
        {n:"Tomato paste",pp:10,u:"g"},
        {n:"Red wine",pp:40,u:"ml"},
        {n:"Beef stock",pp:40,u:"ml"},
        {n:"Dried thyme",pp:0.5,u:"g"},
        {n:"Bay leaves",pp:null,u:""},
        {n:"Oil",pp:8,u:"ml"},
      ],
      method:["Heat oil in potjie over hot coals. Brown lamb neck in batches — deep colour means deep flavour.","Add onion and garlic. Cook until soft.","Add tomato paste. Stir and cook 2 min.","Add wine and stock. Season well.","LAYER — do not stir: add carrots, then potatoes, then butternut on top.","Cover with lid. Simmer over low coals 2–2.5 hours.","Add green beans on top in last 20 min.","THE RULE: do not stir. Serve by spooning layers from top to bottom."],
      tip:"The no-stir rule is sacred in potjiekos. Each layer steams and cooks in sequence. Stirring breaks the layers and makes it a stew. Trust the process.",
      howItFeels:"Time slows down around a potjie. This is not fast food.",
      storage:"Fridge 3 days. Tastes better the next day." },

    { id:"pr_melktert", name:"Melktert", intl:"SA Milk Tart", emoji:"🥧", cuisine:"South African", time:60, serves:8,
      tags:["dessert","bakes","sweet","afrikaner","tart","milk tart"],
      ingredients:[
        {n:"Butter (cold, cubed)",pp:15,u:"g"},
        {n:"Cake flour",pp:25,u:"g"},
        {n:"Icing sugar",pp:5,u:"g"},
        {n:"Egg yolk",pp:0.1,u:"egg"},
        {n:"Cold water",pp:5,u:"ml"},
        {n:"Full cream milk",pp:90,u:"ml"},
        {n:"Sugar",pp:15,u:"g"},
        {n:"Flour",pp:8,u:"g"},
        {n:"Cornflour",pp:5,u:"g"},
        {n:"Egg",pp:0.25,u:"egg"},
        {n:"Butter",pp:5,u:"g"},
        {n:"Vanilla essence",pp:0.5,u:"ml"},
        {n:"Cinnamon (for dusting)",pp:null,u:""},
      ],
      method:["PASTRY: Rub cold butter into flour and icing sugar until breadcrumbs. Add egg yolk and water. Press into tart tin. Refrigerate 20 min. Blind bake at 190°C for 15 min.","FILLING: Heat milk until just below boiling.","Whisk sugar, flour and cornflour together. Add eggs. Whisk smooth.","Slowly pour hot milk into egg mixture, whisking continuously.","Return to pot over low heat. Stir continuously until thick — about 5 min.","Remove from heat. Add butter and vanilla.","Pour into baked shell. Cool. Dust generously with cinnamon.","Refrigerate 2 hours before serving."],
      tip:"The filling thickens quickly once it starts — don't stop stirring or you'll get lumps.",
      howItFeels:"Cinnamon on your fingers, cold tart on a hot day — pure Afrikaner comfort.",
      storage:"Fridge 3 days." },

    { id:"pr_peppermintcrisptart", name:"Peppermint Crisp Tart", emoji:"🍫", cuisine:"South African", time:20, serves:10,
      tags:["dessert","no bake","sweet","chocolate","cream","easy"],
      ingredients:[
        {n:"Tennis biscuits (or similar plain sweet biscuits)",pp:25,u:"g"},
        {n:"Whipping cream",pp:60,u:"ml"},
        {n:"Caramel treat (tinned)",pp:40,u:"g"},
        {n:"Peppermint Crisp chocolate (grated)",pp:15,u:"g"},
      ],
      method:["Whip cream to soft peaks — not stiff.","Fold caramel treat into whipped cream until combined and smooth.","Layer biscuits in a dish in a single layer.","Spread caramel cream mixture over biscuits.","Repeat layers: biscuits, cream mixture, biscuits, cream mixture.","Top with grated peppermint crisp chocolate.","Refrigerate minimum 4 hours — overnight best."],
      tip:"It MUST be made the day before — the biscuits need time to absorb the cream and soften. Grate the chocolate while still cold from the fridge.",
      howItFeels:"Green, minty, nostalgic — every South African school fundraiser ever.",
      storage:"Fridge 3 days." },

    { id:"pr_chakalaka", name:"Chakalaka", emoji:"🫙", cuisine:"South African", time:30, serves:6,
      tags:["relish","spicy","veg","braai side","township"],
      ingredients:[
        {n:"Onion (finely diced)",pp:20,u:"g"},
        {n:"Garlic (minced)",pp:2,u:"g"},
        {n:"Green pepper (diced)",pp:20,u:"g"},
        {n:"Carrots (grated)",pp:30,u:"g"},
        {n:"Tinned baked beans",pp:50,u:"g"},
        {n:"Tinned tomatoes (chopped)",pp:40,u:"g"},
        {n:"Curry powder",pp:2,u:"g"},
        {n:"Paprika",pp:1,u:"g"},
        {n:"Chilli (optional)",pp:null,u:""},
        {n:"Oil",pp:5,u:"ml"},
        {n:"Salt",pp:null,u:""},
      ],
      method:["Heat oil. Fry onion until soft and beginning to colour.","Add garlic, green pepper and carrots. Cook 5 min.","Add curry powder and paprika. Stir and cook 1 min.","Add tinned tomatoes. Simmer 10 min.","Add baked beans. Simmer 5 min more. Season well.","Serve hot or cold as a braai side."],
      tip:"It improves overnight as flavours develop. Non-negotiable braai side.",
      howItFeels:"Spicy, bright, alive — it wakes up everything else on the plate.",
      storage:"Fridge 5 days. Freezer 2 months." },

    { id:"pr_bunny_chow", name:"Bunny Chow — Lamb Curry", emoji:"🍞", cuisine:"South African", time:90, serves:4,
      tags:["durban","curry","bread","street food","lamb"],
      ingredients:[
        {n:"Lamb shoulder (bone-in, chunked)",pp:200,u:"g"},
        {n:"Onion (finely diced)",pp:30,u:"g"},
        {n:"Garlic (minced)",pp:4,u:"g"},
        {n:"Ginger (grated)",pp:4,u:"g"},
        {n:"Tinned tomatoes",pp:60,u:"g"},
        {n:"Potatoes (quartered)",pp:80,u:"g"},
        {n:"Durban curry powder (hot)",pp:5,u:"g"},
        {n:"Turmeric",pp:1,u:"g"},
        {n:"Cumin seeds",pp:1,u:"g"},
        {n:"Curry leaves (fresh or dried)",pp:null,u:""},
        {n:"Oil",pp:8,u:"ml"},
        {n:"White bread loaf (quarter loaf per person)",pp:1,u:"quarter loaf"},
      ],
      method:["Heat oil. Fry cumin seeds until they pop. Add onion — cook until deep golden.","Add garlic, ginger and curry leaves. Fry 1 min.","Add curry powder and turmeric. Stir and cook 2 min.","Add lamb. Brown all over.","Add tinned tomatoes. Season well. Simmer 45 min covered.","Add potatoes. Cook uncovered 20 min more until thick.","Hollow out a quarter loaf of white bread. Fill with hot curry. Replace bread lid."],
      tip:"The curry must be thick and reduced — a watery bunny chow is a sad bunny chow. Always serve with the scooped bread for mopping.",
      howItFeels:"Street food royalty. You need napkins and you don't care.",
      storage:"Curry fridge 3 days. Always make fresh bread." },
  ]
};
